num_clients: 3
num_rounds: 20
batch_size: 128
lr: 0.001
embedding_dim: 8
hidden_dim: 32
dataset: cdc_diabetes
log_dir: logs

# modify those parameters to test different configurations of differnetial privacy
differential_privacy:
  epsilon: 1.0          # Confidentiality budget
  delta: 1e-5            # Confidentiality violation probability
  max_grad_norm: 1.0    # Maximal norm for gradient/embeddings clipping
  noise_multiplier: 0.5