hyperparameters:
  client:
    _target_: fluke.dcp_client.DPClient
    clipping: 1.0 # Gradient clipping norm - to limit the influence of any single data point
    dp_noise_multiplier: 1.2  # Noise multiplier for Gaussian noise - controls the privacy-utility trade-off
    batch_size: 64
    local_epochs: 5
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 1.0e-05
    persistency: true
    scheduler:
      gamma: 1
      step_size: 1
  model: Adult_MLP
  net_args:
    hidden1: 64
    hidden2: 32
  server:
    weighted: true
    lr: 1.0
name: fluke.algorithms.fedavg.FedAVG
