# --- CRASH PARAMETERS ---

# hyperparameters:
#   client:
#     batch_size: 32
#     local_epochs: 5
#     loss: CrossEntropyLoss
#     optimizer:
#       lr: 0.1
#     scheduler:
#       gamma: 1
#       step_size: 1
#   model: MNIST_2NN
#   server:
#     global_step: 2
# name: fluke.algorithms.scaffold.SCAFFOLD


# --- STABILIZED PARAMETERS ---

hyperparameters:
  client:
    batch_size: 64         
    local_epochs: 1        
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.01             
    scheduler:
      gamma: 1
      step_size: 1
  model: MNIST_2NN
  server:
    global_step: 1.0       
name: fluke.algorithms.scaffold.SCAFFOLD